import './About.css';
const About = () => {
  return (
    <div>
      <h1>About Us</h1>
      <p>
        AGRIBIX IS A BUMBLING MANAGEMENT COMPANY FOCUSED ON AMELIORATING THE
        LIVES OF FARMERS ACROSS KENYA .<br /> AGRIBIX SEEKS TO BRIDGE THE GAP
        BETWEEN FARMERS AND THE AGRICULTURE MARKET BY EMPOWERING THEM THROUGH
        EFFICIENT AND EFFECTIVE MICRO-GROUPS. <br />
        THIS IS DONE IN AN EFFORT TO INCREASE THEIR AGRICULTURAL YIELD BY
        PROVIDING THEM WITH NESTLING SERVICES SUCH AS MARKETING OF PRODUCTS,{" "}
        <br />
        EXPORT AND SALE OF YIELD .<br />
        IN ADDITION ,FARMERS WILL HAVE AN OPPORTUNITY TO PURCHASE FARM MATERIAL{" "}
        <br />
        AND UTILITIES THROUGH OUR WEBSITE.
      </p>
      <img src="dan-meyers-IQVFVH0ajag-unsplash.jpg" alt="About Us image" />
    </div>
  );
};

export default About;